### ISSUE TITLE
`gcd` works incorrect with 0

### ISSUE THREAD

**Issue by nickkolok** [juanelas/bigint-crypto-utils#1]
`gcd(6n,0n);` possibly leads to an infinite loop. IMHO, `gcd(x,0n)` and `gcd(0n, x)` should return x (even if x is 0). In any case, such calls shouldn't lead to a freeze, should they?

**Comment by juanelas** [comment]
You are completely right, that was a bug. It is now fixed. Thank you very much for your feedback!
