### ISSUE TITLE
Optimization and random minimum

### ISSUE THREAD

**Issue by Rudxain** [juanelas/bigint-crypto-utils#11]
LCM can be defined as `a / gcd(a, b) * b` and it's guaranteed to return correct values. Some JS engines won't rearrange the expression `a * b / gcd(a, b)` to optimize it, so it's better to do it manually to make sure the memory footprint and speed are as optimal as possible.

Having a RNG with a `min` parameter whose argument isn't allowed to be negative, makes the parameter *almost* useless IMHO. I recommend that negative `min` support should be added to take full advantage of the convenience of a `min` parameter.
I suppose that parameter was added early because implementing it in the future would cause backwards-compatibility issues if someone tried to use the RNG. Adding it early (even though it's incomplete) was a good decision, and I appreciate that.

I want to apologize in advance if I'm unaware of some important fact that may render my suggestions useless or just bad ideas

**Comment by juanelas** [comment]
Thank you @Rudxain for your valuable feedback. LCM is now optimized and randbetween is accepting negative values, which totally makes sense and have little to no impact on efficiency.
