### ISSUE TITLE
Can't be used in worker context

### ISSUE THREAD

**Issue by frangio** [juanelas/bigint-crypto-utils#16]
**Describe the bug**
Requiring the module in the context of an unrelated worker causes it to start listening for messages, and causes errors as it tries to interpret the worker messages.

**To Reproduce**
Run with node.js:

```js
const { Worker, isMainThread, parentPort } = require('worker_threads');
if (isMainThread) {
  const worker = new Worker(__filename);
  worker.postMessage('Hello world');
} else {
  require('bigint-crypto-utils');
  parentPort.once('message', msg => {
    console.log('Received:', msg);
  });
}
```

Results in the following output:

```
Received: Hello world

node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot mix BigInt and other types, use explicit conversions
    at _isProbablyPrime (node_modules/bigint-crypto-utils/dist/cjs/index.node.cjs:468:17)
    at MessagePort.<anonymous> (node_modules/bigint-crypto-utils/dist/cjs/index.node.cjs:785:33)
```

---

I think the fix is to have a dedicated worker file rather than using [`new Worker(__filename)`](https://github.com/juanelas/bigint-crypto-utils/blob/25484ae03f91e3b1a5876b4f5987957df3446d19/src/ts/isProbablyPrime.ts#L30).

**Comment by juanelas** [comment]
It should be fixed right now. Thanks for pointing it out.
