### ISSUE TITLE
Error with creat-react-app

### ISSUE THREAD

**Issue by fabioginzel** [juanelas/bigint-crypto-utils#6]
If i run with 
`npm start`
this line
`console.log(await bigintCryptoUtils.prime(2048))`
give this error
Uncaught (in promise) ReferenceError: bigint_mod_arith__WEBPACK_IMPORTED_MODULE_0__ is not defined

**Comment by juanelas** [comment]
Now it should be fixed. Please update with `npm update`. Thanks for letting me know.

**Comment by fabioginzel** [comment]
tks

**Comment by 2gomobility** [comment]
This error is back

**Comment by fabioginzel** [comment]
this error is back
