### ISSUE TITLE
bug: use wrong _useWorkers value when not supported

### ISSUE THREAD

**Issue by kybarg** [juanelas/bigint-crypto-utils#8]
Seems like line 680 should be, otherwise it doen't work and makes no sense 
```
_useWorkers = true
```

https://github.com/juanelas/bigint-crypto-utils/blob/902e9fc4ddc94fed54939f8daa303c3f094d64b8/src/js/index.js#L667-L684

**Comment by juanelas** [comment]
Than you for reporting the bug! Now it is fixed.
